### ISSUE TITLE
Website not live yet

### ISSUE THREAD

**Issue by Haroenv** [npms-io/npms-analyzer#11]
I'm seeing a `namecheap` domain expired when going to [npms.io](http://npms.io), are you aware of this?

**Comment by satazor** [comment]
The domain has not expired, it was bought recently. The website is not yet live, I'm still working on it! If you would like to speed things up, help would be much appreciated.

**Comment by Haroenv** [comment]
Aha, super, then this issue should be that it isn't live yet :D I'll look what I can do

**Comment by satazor** [comment]
Hehe, the analyzer is pretty much done for the launch milestone. I'm currently doing the tests for it.

**Comment by satazor** [comment]
Closing this
