### ISSUE TITLE
npms shows wrong score for pouchdb

### ISSUE THREAD

**Issue by abnud1** [npms-io/npms-analyzer#114]
If I write pouchdb in the search box then pouchdb is returned first but with a very bad score, bad quality, bad popularity and bad maintenance, this is obviously wrong.

**Comment by atduarte** [comment]
You can check the values that make up the score here: https://api.npms.io/v2/package/pouchdb

If you find something wrong, please warn us.

**Comment by satazor** [comment]
The issue here is that the package name is different than https://github.com/pouchdb/pouchdb/blob/master/package.json#L2 which flags the package has a "fork". We need to review that mechanism.

**Comment by satazor** [comment]
![screen shot 2016-12-13 at 5 00 12 pm](https://cloud.githubusercontent.com/assets/1017236/21150054/a3575100-c155-11e6-9d4b-7aa1f195daa4.png)

**Comment by satazor** [comment]
Oops my last comment was not for this issue, I've deleted it.

**Comment by abnud1** [comment]
@atduarte thanks, well I checked it and many things wrong : starsCount : 34(correct 7869), tests : 0 (right now build is failing but it has 100% coverage), openIssues : 0(correct 115)

**Comment by satazor** [comment]
Closing in favor of #83.

Will be fixed by #147
