### ISSUE TITLE
What is "download acceleration"

### ISSUE THREAD

**Issue by whmountains** [npms-io/npms-analyzer#115]
You mention "download acceleration" as an ranking attribute.  What exactly is that?

**Comment by satazor** [comment]
Basically it measures the rate at which the downloads increase.

We calculate the velocity of downloads count for each month and then we calculate it's acceleration by comparing the latest velocity with previous ones. If the acceleration is positive it means that the downloads count rate is increasing. If it's negative, it means that even if the velocity is positive, the rate is decreasing which means that adoption is decaying. 

Hope I was clear in my explanation. Cheers.

**Comment by whmountains** [comment]
Yes, that makes total sense.  Thank you!
