### ISSUE TITLE
libraries.io

### ISSUE THREAD

**Issue by slang800** [npms-io/npms-analyzer#12]
[libraries.io](https://libraries.io/) seems to have a similar goal to this project. It might be worthwhile to work with them, either offering them more detailed data on npm, or reusing some of their components https://github.com/librariesio

**Comment by satazor** [comment]
I already knew libraries.io and while is an improvement over npm, the search is still very poor.

Also, npms was a side project to experiment with new technologies. We will see in the future if such merge is possible and worthwile.

**Comment by slang800** [comment]
Ah, cool. I'm actually quite interested in the same thing, though so far I've just been downloading the 0.5TB of tarballed packages and doing some basic directory structure & package size analysis with bash.

And I wouldn't suggest a full merge... libraries.io tries to track all libraries, so an npm-specific analysis tool should probably be a separate project. I'm just suggesting general collaboration since they seem to have similar goals.

**Comment by satazor** [comment]
@slang800 npms-io will probably supply the analysis data & scoring for everyone, either via couchdb replication or via elasticsearch scrolling. Having that said, and if they see value in npms data, they could use definitively use it.
