### ISSUE TITLE
do metadata collection in map-reduce?

### ISSUE THREAD

**Issue by slang800** [npms-io/npms-analyzer#16]
I might be off-base with this since I've only just begun to read the code, but have you considered moving the metadata processing from `lib/analyze/collect/metadata.js` into map-reduce? All that data is already in CouchDB anyway, and MR is excellent for bulk processing.

**Comment by satazor** [comment]
Are you referring to all the processing? There's complex stuff in there, including code present in installed modules, e.g.: spdx, moment, etc

**Comment by slang800** [comment]
Yeah, loading modules isn't much of a barrier to map-reduce... Worst-case-scenario, you could just browserify it and load it that way.

**Comment by satazor** [comment]
Advantages of using a map in this case:

- performance

Disadvantages:

- code complexity and understanding.. 1 collector is on the db, the rest are on the code
- we loose logging because there's no easy wait to log stuff in map functions; at the moment logs are unified using `npmlog` and later I will pipe those to logstash and use kibana

Performance is not an issue really anyway. To get you an idea the `cli tasks re-medata` command takes around 5m in my laptop.

**Comment by slang800** [comment]
For the logging bit: I haven't used logstash or kibana, but I do know you can log within view functions and push the couch.log into graylog2.

**Comment by satazor** [comment]
I see. I just think its not worth it, it will increase the complexity the metadata collector, comparing to others. Did you managed to get the analyzer working on your end? Could you measure the time it takes to run that analyzer? A simple `console.time` would do it.

**Comment by slang800** [comment]
Eh, mostly working... I'm getting `AGGREGATION_NOT_FOUND` when I run a command like `./cli.js tasks process-module backbone`, but I'm probably doing something stupid.

**Comment by satazor** [comment]
Oh no, that's a bug on my end. I always test it with an aggregation done and I forgot to protect it.

The process-module command analysis and scores a module, but since there's no aggregation the score can't be done. Give me a sec, I will fix it.

**Comment by satazor** [comment]
Actually that's already protected. It's not a fatal error per-say, just a normal error.

**Comment by satazor** [comment]
To bypass it for now, you may create the aggregation doc on the `npms` database:

```
{
   "_id": "scoring!aggregation",
   "count": 255985,
   "quality": {
       "carefulness": {
           "min": 0,
           "max": 1,
           "mean": 0.5426948063357774
       },
       "tests": {
           "min": 0,
           "max": 1,
           "mean": 0.33069964597526535
       },
       "dependenciesHealth": {
           "min": 0,
           "max": 1,
           "mean": 0.8027828542422347
       },
       "branding": {
           "min": 0,
           "max": 1,
           "mean": 0.11825849170856917
       }
   },
   "popularity": {
       "communityInterest": {
           "min": 0,
           "max": 141477,
           "mean": 128.0597339687902
       },
       "downloadsCount": {
           "min": 0,
           "max": 28687991.666666668,
           "mean": 12922.189745493257
       },
       "downloadsAcceleration": {
           "min": -21871.581582952815,
           "max": 128116.44745053275,
           "mean": 64.89079281744043
       },
       "dependentsCount": {
           "min": 0,
           "max": 20333,
           "mean": 2.402363419731591
       }
   },
   "maintenance": {
       "recentCommits": {
           "min": 0,
           "max": 1,
           "mean": 0.31168388772777483
       },
       "commitsFrequency": {
           "min": 0,
           "max": 1,
           "mean": 0.24771972274169102
       },
       "openIssues": {
           "min": 0,
           "max": 1,
           "mean": 0.535834519611601
       },
       "issuesDistribution": {
           "min": 0,
           "max": 1,
           "mean": 0.5232532275424758
       }
   }
}
```

This was the result of the last aggregation on my laptop.

**Comment by satazor** [comment]
My idea was to later create a docker image to be easy to setup the project for development, but I haven't had the time to invest on it.

**Comment by satazor** [comment]
@slang800 any news?

**Comment by slang800** [comment]
@satazor: I'll open up a new issue if I find any problems to avoid cluttering up this topic

**Comment by satazor** [comment]
As I said, the metadata collection is very fast and it's not worth complicating the project for a marginal speedup. Closing this for now.
