### ISSUE TITLE
link to non-public image

### ISSUE THREAD

**Issue by slang800** [npms-io/npms-analyzer#20]
`https://npms-io.slack.com/files/andreduarte/F0QU3SYJW/twe.png` is mentioned in `lib/scoring/score.js`, but it's not publicly available :cry:

**Comment by satazor** [comment]
You are right, and actually that image is outdated. @atduarte could you generate a newer image that represent the current formula?

**Comment by slang800** [comment]
And PR it into `./docs`, please! :smile:
