### ISSUE TITLE
Analyzer Documentation

### ISSUE THREAD

**Issue by ahmad-abdellatif** [npms-io/npms-analyzer#209]
I have followed each step in the documentation, but I am getting an error:
[2018-02-20T16:01:50.388Z] ERROR (npms-analyzer/58244 on date.encs.concordia.ca): Progress stat failed
    err: {
      "message": "Cannot read property 'value' of undefined",
      "stack": "TypeError: Cannot read property 'value' of undefined\n    at Promise.props.npmsPackagesCount.npmsNano.viewAsync.then (/Users/ahmad/Desktop/npms/npms-analyzer/cmd/util/stats/progress.js:35:40)\n    at Request._callback (/Users/ahmad/Desktop/npms/npms-analyzer/node_modules/nano/lib/nano.js:217:16)\n    at Request.self.callback (/Users/ahmad/Desktop/npms/npms-analyzer/node_modules/request/request.js:186:22)\n    at emitTwo (events.js:126:13)\n    at Request.emit (events.js:214:7)\n    at Request.<anonymous> (/Users/ahmad/Desktop/npms/npms-analyzer/node_modules/request/request.js:1163:10)\n    at emitOne (events.js:116:13)\n    at Request.emit (events.js:211:7)\n    at IncomingMessage.<anonymous> (/Users/ahmad/Desktop/npms/npms-analyzer/node_modules/request/request.js:1085:12)\nFrom previous event:\n    at Timeout.setInterval [as _onTimeout] (/Users/ahmad/Desktop/npms/npms-analyzer/cmd/util/stats/progress.js:35:14)\n    at ontimeout (timers.js:475:11)\n    at Timer.unrefdHandle (timers.js:588:5)"
    }
    module: "stats/progress"

I repeated the steps twice on different machines but I am still getting the same error.

I noticed that there is a change in the documentation in 19-Jan, is there anything missing or need to be changed?

**Comment by satazor** [comment]
The error happened because of a bug in https://github.com/npms-io/npms-analyzer/blob/ade7058b79484e06c7ef69ce8e98688fc038e4be/cmd/util/stats/progress.js#L36 where we assumed that the npms db was not empty.
