### ISSUE TITLE
Analyzer doesn't collect GitHub data

### ISSUE THREAD

**Issue by DokaRus** [npms-io/npms-analyzer#232]
I've noticed that some search results for packages like [this one](https://api.npms.io/v2/package/devextreme) don't contain GitHub data (stargazers, issues, forks etc).
For the package above the `repository` field looks correct. Would you please clarify what is wrong with it?

**Comment by DokaRus** [comment]
@satazor What do you think?

**Comment by satazor** [comment]
@DokaRus should be fixed, thanks for the report
