### ISSUE TITLE
Feature request : fetch tests from the github repository when none are in the NPM package

### ISSUE THREAD

**Issue by xurei** [npms-io/npms-analyzer#233]
Some packages don't provide the tests in the NPM package, I personnaly do that to reduce the package size.
This makes the analysis give a score of 0 for the tests :-( .

It would be great that the analyzer clones the git repository (if provided) and checks the presence of tests there as well. That way, we can keep the best of both worlds : lightweight packages and tests only in the git repository.

What do you think ?

**Comment by satazor** [comment]
@xurei we do download the repo from github if the repository field on the package.json is filled correctly. What package is reporting 0 tests?

**Comment by satazor** [comment]
Bump.

**Comment by xurei** [comment]
@satazor One of mine, but indeed, the repository field was not set.
My bad... I'm closing this.
