### ISSUE TITLE
Improve stemming

### ISSUE THREAD

**Issue by satazor** [npms-io/npms-analyzer#26]
The current stemmer is very loose. We opted for this because the aggressive one was causing some troubles, e.g.: `expression -> express`. Though we are loosing some meaningful results, e.g.: `pm2` contains `process` and `manager` but searching for `process management` does not return it.

We could experiment having both loose and aggressive stemmers as separate fields and give the aggressive stemmer field a lower weight.

**Comment by sindresorhus** [comment]
Example: `glob` should match `globby`.

**Comment by satazor** [comment]
@sindresorhus i've tried the most aggressive stemmer and globby is being transformed to globbi, which will still cause a no match for `glob`. Perhaps we could add a prefix query (e.g.: ngram) instead for cases like that. @atduarte ?
