### ISSUE TITLE
Do not impact finished modules negatively over time

### ISSUE THREAD

**Issue by sindresorhus** [npms-io/npms-analyzer#29]
https://github.com/npms-io/npms-analyzer/blob/master/docs/architecture.md#maintenance

It considers factors like "Most recent commit" and "Commit frequency", but doesn't take into account that often in the npm ecosystem small modules can be finished. Meaning they don't receive frequent commits. Not because they're badly maintained, but rather because they're focused on solving one problem and does it well.

**Comment by satazor** [comment]
You are right. Based on the collected information we can infer with certain certainty that a module is finished, e.g.: if it had > X issues open but they are now closed, it's stable (> 1.0.0) among other characteristics. Then, we would take into consideration if the module is finishing when evaluating the maintenance.

**Comment by satazor** [comment]
@sindresorhus I'm working on this now. Could you give me a small list of your modules that you consider finished?

Also could we agree which aspects contribute to qualifying a module as finished? I'll list what I think is reasonable:

- is stable: v > 1.0.0
- has no open issues (or perhaps a very small number of **recent** issues)
- is not deprecated
- has readme & tests

**Comment by pedro93** [comment]
No open issues may be a misleading factor, there may exist are open issues but these are enhancements or suggestions. Perhaps making the analyser aware of labels and taking that into consideration could give a better indication.

**Comment by satazor** [comment]
I understand your point @pedro93 but if there are open issues requestion features for long time, then the module is not finishes at all. The repo owner should close feature requests if he sees they don't fit.

**Comment by pedro93** [comment]
I am merely suggesting an extra data point for npms to score maintainability. From my experience code breaking enhancement issues tend to stick around for quite a while, typically to allow discuss in the community about it.

**Comment by satazor** [comment]
I see, we could make https://github.com/IndigoUnited/node-gh-issues-stats aggregate counts for labels as well. Though, classifying the module as finished, will only have influence in 2 out of 4 aspects of maintenance. I don't know if its worth it.

**Comment by pedro93** [comment]
I am unfamiliar with the code base so I'll leave the judgment to you if this is too much work for the effort. Another question is the weight that each aspect has to the maintainability ranking. For example are unchanged code bases with 0 open issues but a version under 1.0.0 not maintained or simply matured? In theory it would be the former but the developer might not respect semver.

**Comment by satazor** [comment]
> I am unfamiliar with the code base so I'll leave the judgment to you if this is too much work for the effort. 

Lets wait for @sindresorhus opinion too, so I can make a better judgment myself.

> For example are unchanged code bases with 0 open issues but a version under 1.0.0 not maintained or simply matured? In theory it would be the former but the developer might not respect semver.

At the moment, the `maintenance` does not take into consideration the module stability, but `quality` does.

**Comment by sindresorhus** [comment]
While classifying labels sound hard to get right, it could be a useful indicator, but I think there are lots of other things that are more important factors.

1.0.0 is a good sign of stability.

**Comment by jamestalmage** [comment]
I think it would be helpful to find a large set of modules that receive bad marks for maintenance, but we otherwise consider good. Perhaps we could run a search for "most popular low ranked modules" to find some.
