### ISSUE TITLE
Public scoped packages are not being analyzed

### ISSUE THREAD

**Issue by satazor** [npms-io/npms-analyzer#47]
Apparently the skimbdb registry does not have them, see: https://twitter.com/satazor/status/735107823256866816

Needs investigation.

One thing to note is that the exact-match boost needs to be tweaked so that a boost to "@polymer/polymer" is given when searching for just "polymer".

**Comment by gdi2290** [comment]
+1

**Comment by satazor** [comment]
Until they are available through the registry nothing can be done. We must wait.

**Comment by satazor** [comment]
A new registry endpoint that has scoped modules is now available: https://replicate.npmjs.com

**Comment by satazor** [comment]
I've tried this new registry, but I can't replicate from it. I've reported the problem.

**Comment by bcoe** [comment]
we've replaced replicate.npmjs.com with CouchDB 2.0, you should be able to replicate from it now:

https://replicate.npmjs.com/

**Comment by satazor** [comment]
This has been fixed meanwhile, enjoy searching scoped packages!

**Comment by bcoe** [comment]
\o/ @satazor amazing work.

**Comment by satazor** [comment]
<3
