### ISSUE TITLE
Give exact matches a higher boost

### ISSUE THREAD

**Issue by satazor** [npms-io/npms-analyzer#48]
We are already giving a boost with the phrase prefix query but it needs to be re-evaluated. When searching for `streaming-s3`, the `streaming-s3` itself appears in the second page. It feels right at first, because its score is low but it also feels wrong in some way..

Needs investigation, cc @atduarte 
Reported in: https://twitter.com/tal_asad/status/741985395756257282

**Comment by atduarte** [comment]
I think that if there's an exact name match we should automatically show the package in the first position, not changing the elastic query.

**Comment by atduarte** [comment]
Another bug report: https://www.reddit.com/r/javascript/comments/4nq1ti/npms_a_better_and_open_source_search_for_node/d4620ni

**Comment by pygy** [comment]
In the same vein, https://npms.io/search?term=mithril https://www.npmjs.com/package/mithril

**Comment by satazor** [comment]
I agree @atduarte, I will try to work on this today.

**Comment by satazor** [comment]
See:

https://github.com/npms-io/npms-analyzer/pull/50
https://github.com/npms-io/npms-api/pull/24

**Comment by satazor** [comment]
Merged and fixed.
