### ISSUE TITLE
Search relevance should be improved

### ISSUE THREAD

**Issue by mvila** [npms-io/npms-analyzer#55]
With a search for "pdf" I was expecting to find the most popular PDF generators ([jspdf](https://www.npmjs.com/package/jspdf) and [pdfkit](https://www.npmjs.com/package/pdfkit)) but the result I got was [not really good](https://npms.io/search?term=pdf). Maybe you should give more credit to the GitHub stars?

**Comment by satazor** [comment]
@mvila we can investigate further but they have a quite bad maintenance score..

**Comment by mvila** [comment]
In my opinion, a high number of open issues should not imply that a project is not well maintained. Popular projects have often a lot of open issues because people use issues for many reasons: feature requests, discussions, etc. See [React](https://github.com/facebook/react/issues) for example.

Anyway, why the "pdf" module comes first with a global score of 19?

Also, I think "jspdf" with 6,175 GitHub stars should have a popularity score greater than 34.

**Comment by satazor** [comment]
@mvila ofcourse not, but the ratio of open issues vs closed issues, issues distributions over time, etc certainly does point to badly maintained repositories. You may checkout what contributes to the maintenance here: https://npms.io/about

The point of npms.io is not to suggest popular libraries, but to suggest the more balanced libraries in the ecosystem.

**Comment by mvila** [comment]
Okay but today if we want to generate PDF with JS, there are basically two solutions: jsPDF and PDFKit. So, these projects should have a better ranking don't you think?

**Comment by satazor** [comment]
@mvila we are making some adjustments to scoring.. lets see how it goes.

anyway @atduarte have you read this?

**Comment by atduarte** [comment]
Yes, I have. "pdf" can mean a lot of things: "pdf viewer", "pdf generator", "pdf validator", "pdf convertor", etc. And since all "pdf writer" packages, such as `jspdf`and `pdfkit`, aren't that good, according to the scores, it's normal that they don't show up first.

See https://npms.io/search?term=pdf+writer.

**Comment by satazor** [comment]
Exactly, "pdf" is very vague and it gets worse that both jspdf and pdfkit are not that good overall.
Having that said, I'm closing this issue because there's nothing we can do to improve their own modules.

**Comment by mvila** [comment]
I agree that "pdf" is a very vague search term but querying Google for [js pdf](https://www.google.com/search?q=js+pdf) returns what is (in my opinion) the most expected results: the most popular PDF viewers and generators. My feeling is that you give too much importance to the search terms.
