### ISSUE TITLE
Provide a scoring breakdown to allow for more informed usage decisions

### ISSUE THREAD

**Issue by clayreimann** [npms-io/npms-analyzer#56]
I see [the code](https://github.com/npms-io/npms-analyzer/tree/master/lib/analyze/evaluate) that crunches the numbers, but is there an easy way to inspect how scores are calculated for a particular package?

In my particular case I'm a new maintainer of the [github-api](https://www.npmjs.com/package/github-api) module and I'm trying to figure out why our module's score is so abysmally low when after skimming the calculations used I can't see any place that we fall horribly short.

**Comment by satazor** [comment]
I was planning to include the things that a module is failing in the module page itself, which is not yet done. In the case of `github-api`, the problem is that you have a `gitHead` property in your package.json which points to a very old [commit](https://github.com/michael/github/tree/aa8aa3c8cd5ce5240373d4fd1d06a7ab4af41a36). You should remove that property, because the `npm publish` will set it automatically for you.

**Comment by clayreimann** [comment]
Good to know, in any case it could be useful to provide the details used to calculate the scores to help people make more informed decisions. (I might not care if the project has its own homepage, or a change log)

**Comment by satazor** [comment]
The details are explained in https://npms.io/about which also includes a [link](https://github.com/npms-io/npms-analyzer/blob/master/docs/architecture.md) to a more detailed explanation.

Can this issue be closed?

**Comment by clayreimann** [comment]
It depends on if you feel that implementing the feature is valuable. I read the description of the calculation used, but that doesn't give me any insight into why a particular module's score.

This is what you show on your website currently: 
![image](https://cloud.githubusercontent.com/assets/930039/16155058/38a2428a-3473-11e6-9a9c-1fe6c680fbcb.png)

What that doesn't tell me is what about the code gives it `quality=65`. is it because their code is complex or because it has outdated depenencies? More importantly why is `maintenance=0`, given `babel`'s popularity I can only assume it's the number of open issues but I'd really like to know.

**Comment by clayreimann** [comment]
@satazor Sorry, I guess I missed the part where you said you were going to build a page for the module. That page should satisfy my curiosity.

**Comment by satazor** [comment]
No problemo!

**Comment by aaronjameslang** [comment]
How would this problem be solved today? I have a similar issue, wanting to know exactly what I need to change to improve my score, but https://npms.io/module/react seems to have gone away
