### ISSUE TITLE
Don't link to GitHub repo if it doesn't exists

### ISSUE THREAD

**Issue by sindresorhus** [npms-io/npms-analyzer#70]
In that case, fall back to the npm page.

Example, click the result here: https://npms.io/search?term=alfred-logger

**Comment by satazor** [comment]
The `links` property under the metadata collector has the following structure:

```js
{
    npm: `https://www.npmjs.com/package/${encodeURIComponent(packageJson.name)}`,
    homepage: packageJson.homepage,
    repository: gitInfo && gitInfo.browse(),
    bugs: (packageJson.bugs && packageJson.bugs.url) || (gitInfo && gitInfo.bugs()),
};
```

Technically the `homepage`, `repository` and `bugs` should all be checked. For git repositories we can check against the git collector.. if it failed we should delete the `repository` fields and the `bugs` field if it's also linked to github. Though, people might use other services other than git and we are left of with the `homepage`. We could do a proper validation of the link, doing a request and checking its status code. This would be more reliable.

**Comment by sindresorhus** [comment]
> We could do a proper validation of the link, doing a request and checking its status code. This would be more reliable.

👍 Just do a `HEAD` request and check for status code.

**Comment by satazor** [comment]
@sindresorhus I've done a module and it's ready to be published but I'm undecided about its name: `is-link-working` `test-link`. Which of those do you think it's best? You may suggest others ofcourse.

**Comment by sindresorhus** [comment]
`is-link-working` sounds fine. Unsure about the scope of the module, but `is-url-working` could also work.

**Comment by satazor** [comment]
@sindresorhus the metadata was all re-indexed and it's now live.

**Comment by sindresorhus** [comment]
Woot! 👌😎
