### ISSUE TITLE
Machine learning project

### ISSUE THREAD

**Issue by sammy-SC** [npms-io/npms-analyzer#76]
Hello, I tweeted you two weeks ago (sorry, i was on a backpacking vacation and did not really get a chance to properly sit down and write this).

I am working on a machine learning project which aims to rank node packages based on anything that is available online. To name sources: github archive, NPM, github API. I read your docs and noticed that you already collected most of the data.

Was wondering how interested you would be in collaborating.

**Comment by satazor** [comment]
@sammy-SC Sorry for getting back to you only now. Absolutely! Perhaps it would be better if you could chat on slack. Drop me an email if you want to get invited. My email is on my profile.
