### ISSUE TITLE
Does the algorithm work with monorepos?

### ISSUE THREAD

**Issue by bebraw** [npms-io/npms-analyzer#83]
I'm seeing low quality values for packages using a monorepo. Try searching for Babel or PouchDB for example. Does the algorithm take their different structure into account?

**Comment by satazor** [comment]
@bebraw not at the moment. What do you think it would be the most adequate way to detect such monolithic repos?

**Comment by bebraw** [comment]
Lerna projects rely on convention. You can find `packages` at the root always. There's also that `lerna.json` file.

It gets trickier outside of Lerna. Take something like [Cycle.js](https://github.com/cyclejs/cyclejs/) for example. It uses entirely custom setup.

Perhaps looking into Lerna support would be a starting point given a few notable projects use it already.

**Comment by bebraw** [comment]
It actually gets interesting with something like code coverage. Here's [an example](https://codecov.io/gh/reactabular/reactabular) from a project of mine. Instead of coverage per package, you get it per whole monorepo. The measure isn't completely accurate as some packages are missing tests at the moment.

Getting coverage per package would be harder and you would have to inspect the coverage information per package directory.

**Comment by mischah** [comment]
Hej @satazor,

we are having a problem with that regarding our new [generator list](http://yeoman.io/generators/).

There is at last one Yeoman generator which is stored monorepo in a so called »monorepo«:
https://github.com/redfin/react-server/tree/master/packages/generator-react-server

As a result the [response ](https://api.npms.io/v2/package/generator-react-server) from the npms API doesn’t contain the `github` object which leads to `0` stars instead of `2895` in the generator list. I can feel the pain of the maintainers of this generator :confounded:

Is there something you can do about that?

cc/ @SBoudrias @zckrs

**Comment by satazor** [comment]
Hey @mischah,

Currently there's no to support packages that are within a monolithic repository. Though, I think that adding support to it it's not hard, but requires some effort. Doing a superficial analysis, "fixing" the `downloaded.dir` [here](https://github.com/npms-io/npms-analyzer/blob/master/lib/analyze/index.js#L161) would make it work. Specifically, we could do a `glob('**/package.json')` and find a package.json whose `name` matches the package name. Then, `downladed.dir` would be the directory in which the package.json was found.

I'm willing to accept a PR that implements this assuming that my suggestions works well!

**Comment by mischah** [comment]
Thanks for instant feedback 💖

**Comment by Daniel15** [comment]
> It actually gets interesting with something like code coverage. Here's an example from a project of mine. Instead of coverage per package, you get it per whole monorepo.

That seems like a limitation with the code coverage tool. In other environments such as C#/.NET, monorepos have been used basically forever (I haven't seen **any** .NET projects that didn't have multiple projects/packages in the one repo) and all the code coverage tools let you view coverage by project or by namespace.

**Comment by bebraw** [comment]
@Daniel15 Correct.

**Comment by satazor** [comment]
Closing in favor of https://github.com/npms-io/npms/issues/13
